### ISSUE TITLE
unsigned-corim-map uses temporary global code points 47110

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats/ietf-corim-cddl#105]
d9 b806                                 # tag(47110)
   d9 b807                              # tag(47111)
      a2                                # map(2)
         00                             # unsigned(0)
         50                             # bytes(16)
            284e6c3e5d9f4f6b851f5a4247f243a7 # "(Nl>]\x9FOk\x85\x1FZBG\xF2C\xA7"
         01                             # unsigned(1)
         d9 b80d                        # tag(47117)

These should use IANA registered values starting at 500

**Comment by thomas-fossati** [comment]
mmh is that still true?  Could you please check against the newly generated examples?

**Comment by nedmsmith** [comment]
They are fixed. I was working from stale pretty files.

**Comment by thomas-fossati** [comment]
> They are fixed. I was working from stale pretty files.

OK, I'm closing this then.
