### ISSUE TITLE
entity-entry should be its own namespace

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats/ietf-corim-cddl#12]
CoRIM, XcoRIM, CoMID, and CoSWID all depend on entity-entry. 

The broad dependency suggests to me that entity-entry should be a stand-alone namespace. 

It needs to have an extensible roles approach - for example allowing each client to register its roles names. But this could be done using "mynamespace." convention. 

An entity should be able to become a w3C DID eventually.

**Comment by nedmsmith** [comment]
For now agree to have a new entity entry for corim and xcorim and another for comid (while keeping coswid). 3 entity-entries total (entity-entry, corim.entity-map, comid.entity-map).

**Comment by yogeshbdeshpande** [comment]
I am happy to take this item and work on it!

**Comment by nedmsmith** [comment]
Was this part of PR#17?

**Comment by yogeshbdeshpande** [comment]
As informed, PR#17 will be re-worked to have individual roles. Issue #12 will address complete entity-entry including roles.
