### ISSUE TITLE
corim-meta-map should be CBOR encoded

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats/ietf-corim-cddl#132]
The current definition `corim.meta => corim-meta-map` forces the COSE library to understand the CoRIM Meta type (in particular any custom tagging.)
This is impractical in cases where the CoRIM developer doesn't have the ability to modify the COSE library either because it is closed source or because it doesn't allow type extensibility around the `* label => values` fields.

We should therefore make it opaque by CBOR encoding it, i.e.: `corim.meta => bstr .cbor corim-meta-map`

**Comment by nedmsmith** [comment]
agree.
