### ISSUE TITLE
Xcorim entities and roles

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats/ietf-corim-cddl#136]
The Xcorim structure is similar to the CoRIM structure having a signer in the signed-xcorim and a creator in the unsigned xcorim. Should the xcorim schema be adjusted similarly to PR#130?

**Comment by thomas-fossati** [comment]
I think so 👍

**Comment by nedmsmith** [comment]
I'm trying to keep CDDL in sync with TCG spec - can this PR take priority?

**Comment by thomas-fossati** [comment]
sure, I'll provide a fix shortly.
