### ISSUE TITLE
avoid empty objects when all elements are optional

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats/ietf-corim-cddl#18]
There are a few objects definitions where all elements are optional.  The list currently includes, `claims-map`, `element-name-map`, `element-value-map`.  If we intend these to be populated with at least one element, we could add the following CDDL:
```
non-empty<M> = (M) .and ({ + any => any })
```
and then:
```
? comid.claims => non-empty<claims-map>
```

**Comment by nedmsmith** [comment]
Yes, the intent is for maps that are all optional to have one or more provided values. The normative language in referencing specifications is intended as the way to capture these requirements. 
It is nevertheless appropriate for the parser to throw an error if there is an empty structure (I think). 
I'm weary of too many CDDL-isms creeping into the specification that makes it more difficult for non-experts to comprehend. Though "non-empty" seems pretty benign.
