### ISSUE TITLE
"metadata" is imprecise

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats/ietf-corim-cddl#25]
We now know that when we say `metadata` in `module-metadata-map` and `tag-metadata-map` what we really mean is `identifiers` or `id`.  We should update those two names accordingly.

**Comment by nedmsmith** [comment]
I'm not following. module-metadata-map contains module-name (which is an element-name-map) and module-version. tag-metadata-map contains tag-id and tag-version. tag-id is a globally unique (instance) value and module-name is a class identifier. These are different identification semantics and therefore shouldn't be equated IMO.

**Comment by thomas-fossati** [comment]
What I'm suggesting is that we rename `module-metadata-map` to `module-identifier-map`, and similarly for `tag-metadata-map`.

**Comment by thomas-fossati** [comment]
This has been done with open-heart surgery in the following commits:

* ca188a1823c5e75084e91ab64a375072ff66f898
* 4074284005536d6ed1ee1ac36f96852de9219f83
* da85edc96af9d7cace64abb2daa46707acd3ac12
