### ISSUE TITLE
add element-name to identity-claim-map

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats/ietf-corim-cddl#31]
We decided to add 'element-name-map' to the 'identity-claim-map' but this change needs a PR.

numeric code point: 0 
text code point:  comid.element-name 
type: element-name-map 
optional: T 
Extension point:  '$$identity-claim-map-extension'
Description: element-name   MAY match the element-name or equivalent fields of a module name in another   CoMID tag or the element-name of a claim in another CoMID tag.

**Comment by thomas-fossati** [comment]
My memory is terrible, what is the use case for this?

**Comment by thomas-fossati** [comment]
Note that, in the identity claim map, code point 0 is already allocated to `comid.device-id`.  We can mint a new `comid.identity-element-name` (similar to what we have in the instance claims map) and call it 2.

**Comment by nedmsmith** [comment]
I'm not following 'comid.identity-element-name' vs. 'comid.element-name' code point collision since we reuse 'comid.element-name' in the other claims maps.  I put added element-name-map to code point = 0 to align with the other structures, but making it 2 instead of 0 isn't a big deal.
