### ISSUE TITLE
why is `element-name-map` mandatory in `endorsed-value-map` ?

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats/ietf-corim-cddl#33]
I can't recall why in `endorsed-value-map` we made `element-name-map` mandatory?

I.e., could we have instead:
```
endorsed-value-map = non-empty<{
  ? comid.element-name => element-name-map
  ? comid.element-value => element-value-map
  * $$endorsed-value-map-extension
}>
```

**Comment by nedmsmith** [comment]
maybe it is historical. The element-name is the 'key' in key-value pair. So, it plays an important role in matching claims. The Endorsement spec section 6 now has an improved algorithm section that helps describe matching. The schema can be more flexible in terms of optionality, but the normative might be tighten it up.

**Comment by thomas-fossati** [comment]
we have a couple of cases where it is redundant - as it just replicates the "outer" module name - which may benefit from elision.

**Comment by nedmsmith** [comment]
So the semantics would be that if there is a claim without an element-name it defaults to the module-name context?

**Comment by thomas-fossati** [comment]
> So the semantics would be that if there is a claim without an element-name it defaults to the module-name context?

yes
