### ISSUE TITLE
concise-reference-integrity-manifest-group-choice 

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats/ietf-corim-cddl#34]
We decided to make concise-reference-integrity-manifest a group choice with a single element for now where:
numeric code point: 0
text code point: 'corim'
type: concise-reference-integrity-manifest-group-choice
description: 'top level corim structure'

concise-reference-integrity-manifest-group-choice is defined as;
numeric code point: 0
text code point: corim.unsigned-corim
type: #6.47111(unsigned-corim-map)

and

numeric code point: 1
text code point: corim.signed-corim
type: #6.47112(signed-corim-map)

**Comment by thomas-fossati** [comment]
I don't think the above can be translated to CDDL.

What is that we want to achieve?  If we want to let CoRIM be choice among a few well-defined (but extensible) options, we could just:
```
corim = #6.10000($concise-reference-integrity-manifest-type-choice)

$concise-reference-integrity-manifest-type-choice /= #6.47111(unsigned-corim-map)
$concise-reference-integrity-manifest-type-choice /= #6.47112(signed-corim-map)
```

**Comment by nedmsmith** [comment]
Yes, that is what I was thinking would be the CDDL way to handle it.

**Comment by thomas-fossati** [comment]
ok then :-)
