### ISSUE TITLE
corim-entity-map should have multiplicity

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats/ietf-corim-cddl#35]
The corim-entity-map should have multiplicity of 1-or-more so that if the signer is also the manifest-creator this role can be included too.

**Comment by thomas-fossati** [comment]
Don't we already have 1:n?  Current CDDL says:
```
corim-meta-map = {
  corim.signer => one-or-more<corim-entity-map>
  ? corim.validity => validity-map
}
```

**Comment by nedmsmith** [comment]
My mistake. I misread it.
