### ISSUE TITLE
Possible naming inconsistency in Instance claim map

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats/ietf-corim-cddl#43]
Currently, `instance-claim-map` has:
https://github.com/ietf-rats/ietf-corim-cddl/blob/3be51928b05e6a8034aef01b80645d936729ba4c/concise-mid-tag.cddl#L76
Should that be `comid.element-name` instead?

**Comment by nedmsmith** [comment]
Yes, that is how it is in the endorsement spec.
