### ISSUE TITLE
`digests-type` looks dodgy

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats/ietf-corim-cddl#46]
`digests-type` is currently defined as:
```
digests-type = [ hash-entry / [2* hash-entry] ]
```
which looks wrong in a couple of ways:
* _substantial_: there is a spurious wrapping array;
* _typographical_: should use the `one-or-more` macro.

ISTM, it should instead look like this:
```
digests-type = one-or-more<hash-entry>
```

**Comment by henkbirkholz** [comment]
correct. how did that spawn into reality?

**Comment by thomas-fossati** [comment]
> correct. how did that spawn into reality?

That is actually a very good question, which I am not prepared to answer though :-)

**Comment by nedmsmith** [comment]
This is the convention used in coswid.
