### ISSUE TITLE
Align CoMID entity name

### ISSUE THREAD

**Issue by yogeshbdeshpande** [ietf-rats/ietf-corim-cddl#49]
Align CoMID Entity name to be consistent with other usage

**Comment by thomas-fossati** [comment]
could you please unpack this a bit? :-)

**Comment by yogeshbdeshpande** [comment]
CoMID Entity name is rigidly set as text in the current version of CDDL.

This issue aligns the setting of entity_name to be a $entity-name-type-choice which allows future extensibility and also
to be consistent with other usage of Entity name at other places within CoRIM CDDL.

**Comment by yogeshbdeshpande** [comment]
> could you please unpack this a bit? :-)

Done!

**Comment by thomas-fossati** [comment]
fixed by #50
