### ISSUE TITLE
instance values look more like identifiers...

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats/ietf-corim-cddl#57]
Is `value` in `instance-value-group-choice` the right name?  All of these (except for, maybe, IP addresses) look like proper instance identifiers. 

https://github.com/ietf-rats/ietf-corim-cddl/blob/2702ec653ad7f1ec01036f83a969f9a8a2137163/concise-mid-tag.cddl#L80

In light of #51, which adds an element **value** to the instance object, we should probably revise this.

**Comment by thomas-fossati** [comment]
> In light of #51, which adds an element **value** to the instance object, we should probably revise this.

In particular, ISTM that we could give "instance claims" a more uniform treatment by making them a sub-case of the already existing endorsed/reference-claims pair.

**Comment by nedmsmith** [comment]
I don't have a strong opinion. I think both are correct semantically. You would have to do differential privacy analysis to know just how unique the instance value is. What would be the threshold of uniqueness that changes an instance value to an instance identifier?
