### ISSUE TITLE
How to handle endianness

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats/ietf-corim-cddl#61]
The current convention for endianness seems workable for reference measurements (aka 'vendor' decides endianness and constructs both tag and evidence such that verifier doesn't care about endianness). However, for endorsed claims and instance claims verifier might need to know endianness semantics. For example, if a policy expects to inspect specific element-name / element-value / etc... values against values specified in a policy, then the verifier will need to understand endianness. 

One option is to encode endianness into the data set.

Another option is to declare the endianness convention for each attribute in a spec. 

Other options?

**Comment by nedmsmith** [comment]
Someone thought CBOR defines endianness in all cases. Is this true?

**Comment by thomas-fossati** [comment]
> Someone thought CBOR defines endianness in all cases. Is this true?

https://www.rfc-editor.org/rfc/rfc8949.html#section-1.2-2

**Comment by nedmsmith** [comment]
Is JSON aligned similarly?

In other words can someone reading CDDL be unambiguous about endianness regardless of which encoding is selected (JSON/CBOR)?

From: Thomas Fossati ***@***.***>
Reply-To: ietf-rats/ietf-corim-cddl ***@***.***>
Date: Monday, May 17, 2021 at 9:56 AM
To: ietf-rats/ietf-corim-cddl ***@***.***>
Cc: "Smith, Ned" ***@***.***>, Author ***@***.***>
Subject: Re: [ietf-rats/ietf-corim-cddl] How to handle endianness (#61)


Someone thought CBOR defines endianness in all cases. Is this true?

https://www.rfc-editor.org/rfc/rfc8949.html#section-1.2-2

**Comment by thomas-fossati** [comment]
> Is JSON aligned similarly? In other words can someone reading CDDL be unambiguous about endianness regardless of which encoding is selected (JSON/CBOR)?

https://datatracker.ietf.org/doc/html/rfc8259#section-8.1 first para: UTF-8 is a MUST so there is no ambiguity.

**Comment by nedmsmith** [comment]
For all practical purposes, then, CDDL is big-endian?

From: Thomas Fossati ***@***.***>
Reply-To: ietf-rats/ietf-corim-cddl ***@***.***>
Date: Monday, May 17, 2021 at 10:27 AM
To: ietf-rats/ietf-corim-cddl ***@***.***>
Cc: "Smith, Ned" ***@***.***>, Author ***@***.***>
Subject: Re: [ietf-rats/ietf-corim-cddl] How to handle endianness (#61)


Is JSON aligned similarly? In other words can someone reading CDDL be unambiguous about endianness regardless of which encoding is selected (JSON/CBOR)?

https://datatracker.ietf.org/doc/html/rfc8259#section-8.1 first para: UTF-8 is a MUST so there is no ambiguity.

**Comment by thomas-fossati** [comment]
> For all practical purposes, then, CDDL is big-endian?

yes
