### ISSUE TITLE
Min SVN 

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats/ietf-corim-cddl#62]
There is a use case for a vendor specifying a maximum SVN value. If the maxsvn is reached, and if the reported svn in evidence is greater than maxsvn then the verifier should fail evidence matching.

If the endorsed svn is greater than maxsvn then that shouldn't happen and is a failure case. 

Th If the reported svn greater than the endorsed svn but less than maxsvn, then possibly there was an update that bumped the svn but didn't update the endorsement tag/manifest. Possibly, a policy is used to determine if svn is acceptable? 

The schema should nevertheless support a maxsvn along with current svn.

**Comment by thomas-fossati** [comment]
```
svn-type = {
  comid.svn: int
  comid.min-svn: int
}
```

**Comment by nedmsmith** [comment]
These are the verifier rules: (CX is the Ref value and CY is the Evic
d)	IF CX contains ‘svn’ AND CY contains ‘svn’ with a different integer value THEN fail claims verification. 
e)	IF CX contains ‘min-svn’ AND CY contains ‘svn’ that is less than ‘min-svn’ THEN fail claims verification.

**Comment by nedmsmith** [comment]
These are the verifier rules that need to be supported:
-	IF CX contains ‘svn’ AND CY contains ‘svn’ with a different integer value THEN fail claims verification. 
-	IF CX contains ‘min-svn’ AND CY contains ‘svn’ that is less than ‘min-svn’ THEN fail claims verification.

Note: CX is ref value; CY is evidence.
