### ISSUE TITLE
typographical consistency

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats/ietf-corim-cddl#7]
This is to track the "typographical consistency" task.

The following issues that were filed in the draft-birkholz repo are subsumed here:

* ietf-rats/draft-birkholz-rats-corim#54
* ietf-rats/draft-birkholz-rats-corim#58
* ietf-rats/draft-birkholz-rats-corim#59

**Comment by thomas-fossati** [comment]
CoMID has been done in #8 

CoRIM is still TODO.

**Comment by nedmsmith** [comment]
CDDL doesn't have the ability to declare namespaces (e.g. comid, coswid etc.) We use the convention to prepend the namespace name with a dot separator (e.g. comid.language). We don't plan to apply this to type definitions.
