### ISSUE TITLE
best way to handle multiplicity in measurements

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats/ietf-corim-cddl#72]
What is the best way to structure measurements that have multiple different values for the same environment?  IOW, is there a preferred way to represent a [multimap](https://en.cppreference.com/w/cpp/container/multimap) in CDDL?

Current:
```
[
  { k1: v1 },
  { k1: v2 },
  ...
]
```
Alternative:
```
{
  k1: [ v1, v2, ... ]
}
```

**Comment by nedmsmith** [comment]
Added alternative form to main branch.
