### ISSUE TITLE
Don't delete .cbor files 

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats/ietf-corim-cddl#90]
Is it possible to retain the diagnostic .cbor files rather than cleaning them up as part of running tests? This will make them available for inspection by a human.

**Comment by thomas-fossati** [comment]
For later inspection we could send their cbor2pretty output to the GitHub action log.  Would that work for you?

**Comment by nedmsmith** [comment]
Yes.

**Comment by nedmsmith** [comment]
What tool converts .cbor to ascii?

**Comment by thomas-fossati** [comment]
`cbor2pretty.rb`
