### ISSUE TITLE
tags allocation

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats/ietf-corim-cddl#93]
We need to allocate global namespace tags as current spec is using place holders.
Process:
- create a pull request on IANA resources.
- Add to IANA considerations content.
- We need to update this repo once the actual numbers are allocated by IANA.

**Comment by thomas-fossati** [comment]
We have around 15 tags to register (`grep '#6\.' *cddl | cut -d':' -f2 | sort -u | wc -l`).

I have taken a look at the [CBOR Tags registry](https://www.iana.org/assignments/cbor-tags/cbor-tags.xhtml#tags) and we seem to have a couple of options:
1. Scrape the "Unassigned" codes in the 48-109 range, there are 28 of them at the moment, which is more than enough; or
2. Grab a contiguous chunk from the 279-1000 range.

The advantage of option 1. is those tags consume 1 byte vs 2 bytes of option 2.
The advantage of option 2. is we would avoid competition and therefore the risk of renumbering halfway through.

My preference would be option 2 -- say, starting at 500.

@henkbirkholz @yogeshbdeshpande @nedmsmith ?

**Comment by nedmsmith** [comment]
I'm fine with option 2. Save the 1-byte tags for evidence formats that are cbor encoded.

**Comment by thomas-fossati** [comment]
Hearing no counter argument I'm going to prepare a PR for option 2.
