### ISSUE TITLE
IANA registrations

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats/ietf-corim-cddl#94]
We need to reserve "application/rim+cbor" (?) content type and file extension ".corim"

**Comment by thomas-fossati** [comment]
We need either the I-D or the TCG spec to be published and then we can proceed with the [application for the Media Type and the file extension](https://www.iana.org/form/media-types)

**Comment by nedmsmith** [comment]
This also should include xcorim (.xcorim) ("application/xrim+cbor")

**Comment by thomas-fossati** [comment]
Short summary of what we need:
* CBOR tags registration
* Media types and file extensions registration
* Set up the CoMID registry
* Set up the CoRIM registry

**Comment by henkbirkholz** [comment]
This is the wrong repo. Transplanted the summary here: https://github.com/ietf-rats/draft-birkholz-rats-corim/issues/73
