### ISSUE TITLE
ban COSE-Keys

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats/ietf-corim-cddl#97]
No one came back to me on the COSE mailing list regarding the asymmetry between COSE_Key and JWK.

I propose we ditch the COSE-native way of dealing with keys and resort to what we have already done for key chains -- i.e., use base64 string encodings of the usual DER stuff.

**Comment by nedmsmith** [comment]
What changes would be needed?

**Comment by thomas-fossati** [comment]
something along these lines:
```
+pkix-base64-key-type = tstr
 pkix-base64-cert-type = tstr

 verification-key-map = {
   ; Verification key (typically a public key)
-  comid.key => COSE_Key
+  comid.key => pkix-base64-key-type
```

**Comment by nedmsmith** [comment]
OK
