### ISSUE TITLE
criticality flag

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats/ietf-corim-cddl#99]
When Endorser creates reference measurements, the generalized verifier needs to know the criticality of the reference values. There are several ways to communicate criticality.

1) The Attester Evidence contains criticality. If Verifier doesn't recognize the Evidence then Verifier must fail.
- difficult to ensure all forms of Evidence supports this (EAT, TcBInfo, SPDM, etc...)

2) Endorsements contains criticality. If the Verifier doesn't recognize the Reference Values, then fail.
2.a) Add criticality flag inside the triple - difficult to do since we've frozen.
2.b) Add criticality as an extension to the tag.
2.c) Add criticality to a profile.
2.d) Add a supplemental RIM that contains criticality information.

2a is probably the cleanest but hardest to do at this point.

**Comment by thomas-fossati** [comment]
(unsurprising) +1 for 2.c) from my side :-)

**Comment by nedmsmith** [comment]
We need a way to control how profiles affect the corim. If a profile is defined then Verifier needs to know whether to fail if the profile is not recognized. If we are adding profiles to corim (possibly as an extension to unsigned-corim-map then we should add a list of $class-id-type-choice to unsigned-corim-map that is a list of OIDs/UUIDs of profiles that the Verifier MUST recognize.
